### ISSUE TITLE
Flogogen trigger does not create a workable trigger OOB

### ISSUE THREAD

**Issue by tibmatt** [TIBCOSoftware/flogo-cli#116]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[] enhancement request
[] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
flogogen trigger <name of trigger> generates an incomplete _test.go Currently it is possible to take the trigger as generated and test it. 

**Expected behavior:**
Similar to activity. Would have expected the generated trigger to 'work' 
**Minimal steps to reproduce the problem (not required if feature enhancement):**
flogogen trigger testTrigger
cd testTrigger
go test
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & verison if webui, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by fm-tibco** [comment]
Fixed in PR #118 and merged into master
