### ISSUE TITLE
Flogo not get installated on WSL for windows (Ubuntu 22.04)

### ISSUE THREAD

**Issue by Shadab995** [TIBCOSoftware/flogo-cli#131]
Hello ,

I have installed both windows and linux go version 1.18.6 but still when I'm executing the following commands

go install github.com/project-flogo/cli/...@latest

It doesn't install 'flogo'.

I also tried using the other way 
git clone https://github.com/project-flogo/cli.git
cd cli
git checkout test_branch
go install ./... 

but still the same error .

Can you please help me on that. It's very important for me . I have a deadline.

Thank you

**Comment by mellistibco** [comment]
What is the error you're getting? I'm not able to reproduce the issue.

**Comment by Shadab995** [comment]
Thank you for the quick response .

the error is flogo is not getting installed.

when I'm trying to use flogo it gives me the error : 'flogo' not found

**Comment by mellistibco** [comment]
is $GOPATH/bin added to your PATH env var?

**Comment by Shadab995** [comment]
Yes , GOPATH = C:\Program Files\Go\bin

and also via ubuntu  in Path : %USERPROFILE%\go\bin

**Comment by mellistibco** [comment]
Is the flogo binary in go/bin? What happens if you:

```
cd cli/cmd/flogo
go build
```

**Comment by Shadab995** [comment]
It is showing me this error with Go version 18.6
![Screenshot (8)](https://user-images.githubusercontent.com/39089713/193879143-2dbe81dc-f206-4195-9470-aaa2c28f547c.png)


and this one with Go version 1.12.7

![Screenshot (9)](https://user-images.githubusercontent.com/39089713/193879440-800e1622-6b8c-4694-8c62-31ef89a82b79.png)

**Comment by mellistibco** [comment]
I suspect there may be an issue with your installation of go... Is it possible to remove your previous version and install again? All of the errors that you've shown are not within the Flogo CLI code but rather part of go...

**Comment by Shadab995** [comment]
Can you tell me what is the specific version of go suitable for Flogo ?

**Comment by mellistibco** [comment]
Any recent version should suffice. I'm currently using 1.19.

**Comment by Shadab995** [comment]
> Is the flogo binary in go/bin? What happens if you:
> 
> ```
> cd cli/cmd/flogo
> go build
> ```

I can see a file called as "flogo" being created but it's not readable. any idea what can be done 
?

**Comment by mellistibco** [comment]
Great, that's the flogo CLI binary. Feel free to try go install again or manually copy that over to GOPATH/bin and then run execute the flogo CLI as you normally would.

You may have to chmod the file so that you can execute it, jfyi...

**Comment by Shadab995** [comment]
Thank you so much for your help.. it worked.
