### ISSUE TITLE
Flogo CLI Mac OS X Setup Problem

### ISSUE THREAD

**Issue by joesan** [TIBCOSoftware/flogo-cli#24]
I have a problem when I was trying to get the Flogo cli on my Mac OS:

Joesans-MacBook-Pro:~ jothi$ go get github.com/TIBCOSoftware/flogo-cli/...
package github.com/TIBCOSoftware/flogo-cli/cli
	imports bufio: unrecognized import path "bufio" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports flag: unrecognized import path "flag" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports encoding/json: unrecognized import path "encoding/json" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports io: unrecognized import path "io" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports io/ioutil: unrecognized import path "io/ioutil" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports net/http: unrecognized import path "net/http" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports net/url: unrecognized import path "net/url" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports os: unrecognized import path "os" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports os/exec: unrecognized import path "os/exec" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports path/filepath: unrecognized import path "path/filepath" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports runtime: unrecognized import path "runtime" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports strings: unrecognized import path "strings" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports text/template: unrecognized import path "text/template" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports unicode: unrecognized import path "unicode" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports unicode/utf8: unrecognized import path "unicode/utf8" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports sort: unrecognized import path "sort" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/cli
	imports sync: unrecognized import path "sync" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports bytes: unrecognized import path "bytes" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports compress/gzip: unrecognized import path "compress/gzip" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports encoding/base64: unrecognized import path "encoding/base64" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports errors: unrecognized import path "errors" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports reflect: unrecognized import path "reflect" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports strconv: unrecognized import path "strconv" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports log: unrecognized import path "log" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports math: unrecognized import path "math" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports net: unrecognized import path "net" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports regexp: unrecognized import path "regexp" (import path does not begin with hostname)
package github.com/TIBCOSoftware/flogo-cli/flogo
	imports time: unrecognized import path "time" (import path does not begin with hostname)

I would therefore need some help please!

**Comment by OneEricJohnson** [comment]
This looks like you've got a problem with your Go configuration, not a
problem specific to flogo. It looks like your GOROOT environment variable
is either not defined, or not defaulting properly for your environment. The
packages that your message says are not being found all belong to a
standard Go library.

Try doing a go get of "github.com/pkg/errors", and I think you'll see the
same kinds of problems.

Eric.

**Comment by joesan** [comment]
Yes! you were right! The problem was that I had GOROOT also set and it seems I actually do not need it. I only need a GOPATH to be set!

**Comment by shubhamgujarathi07** [comment]
@joesan What did you do to unset the GOROOT? I am facing a similar error but when i set the GOROOT to blank any of the `Go` commands dont work! It says unable to find the GOROOT Directory.
