### ISSUE TITLE
Getting started not working => flogo: command not found

### ISSUE THREAD

**Issue by AntAreS24** [TIBCOSoftware/flogo-cli#26]
I'm starting with Flogo. I've install Go 1.7.5 on a RaspeberryPi 3B and I can compile a Go app.

I've followed the pre-requisit steps without any error, but I'm getting an error when I try to create the project:
`$ go get github.com/constabulary/gb/...`
`$ go get github.com/TIBCOSoftware/flogo-cli/...`
`$ ls $GOPATH/pkg/linux_arm/github.com`
`constabulary pkg TIBCOSoftware xeipuuv`
`$ pwd`
`/home/pi/work/src`
`$ flogo create helloflogo`
`bash: flogo: command not found`

Do I need to manually add flogo bin to the path? If yes, please add this to the get started steps.

**Comment by mellistibco** [comment]
Add $GOPATH/bin to your PATH environment variable.

**Comment by AntAreS24** [comment]
Yes, I did that and it worked. Thanks.
