### ISSUE TITLE
MacOS/Sierra flogo-cli getting started issue...

### ISSUE THREAD

**Issue by stevefister** [TIBCOSoftware/flogo-cli#27]
Following the readme:

Installed Go latest
Set Go Path - export PATH=$PATH:/usr/local/go/bin
Installed gb - go get github.com/constabulary/gb/...
Installed Flogo - go get github.com/TIBCOSoftware/flogo-cli/...
Download myflow.json to work folder
run - ./flogo create myApp

Error: Cannot create flogo project [myApp], gb is not installed

Am I missing something here? Thanks!

**Comment by fcastill** [comment]
You also need to set your GOPATH (or workspace) and add `$GOPATH/bin` to your PATH env variable.

**Comment by stevefister** [comment]
Ah, yes, that worked. Thank you!
