### ISSUE TITLE
flogoapp build issues

### ISSUE THREAD

**Issue by torresashjian** [TIBCOSoftware/flogo-cli#38]
In the new flogoapp build process there are a few small issues:

- flogo.json is not in the bin directory
- flogo.json does not have type id for root task
- flogoapp build adds flows.go to it even though it is not needed

**Comment by fm-tibco** [comment]
- flogoapp build will copy the flogo.json to the build directory
- generated root task now has "type":1
- cannot reproduce creation of flows.go when executing build command

**Comment by torresashjian** [comment]
Issues fixed.
