### ISSUE TITLE
Unable to install flogo on Windows

### ISSUE THREAD

**Issue by Adirio** [TIBCOSoftware/flogo-cli#54]
I followed the README.md steps and did not manage to install flogo on Windows:

1. I installed a clean Go instance and set `PATH` env variable (`go version` yields `go version go1.8.3 windows/amd64`)
2. Created a directory called `C:\Users\MY_USER\Go\src` as suggested by Go
3. Executed `go get github.com/constabulary/gb/...`. Two directories were created, `C:\Users\MY_USER\Go\src\constabulary` and `C:\Users\MY_USER\Go\src\pkg`
4. Executed `go get github.com/TIBCOSoftware/flogo-cli/...`. Two directories were created, `C:\Users\MY_USER\Go\src\TIBCOSoftware` and `C:\Users\MY_USER\Go\src\xeipuuv`

The README.md file starts using `flogo` commands afterwards but it is not being recognized as a comand. Do I need to build something? Or set some other path to `PATH`?

**Comment by apandurangi** [comment]
@Adirio , Can you confirm if you have also added `bin` folder of your go workspace in `PATH` environment?

In this case, `C:\Users\MY_USER\Go\bin` (if I assume that is your go workspace but not the go installation directory)

**Comment by Adirio** [comment]
That was the problem, yes. I didn't realize there was a new `bin` directory in my workspace.

Thank you for your help, closing the issue.
