### ISSUE TITLE
Newly added dependancies are not getting downloaded with flogo build api (rebuilding)

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/flogo-cli#56]
Steps:
Create a flow app
edit flogo.json and add new dependancy (lets say new trigger)
use flogo-cli/app/api.BuildApp() api for building the binary

Issue: newly added dependancies are not getting downloaded.

**Comment by retgits** [comment]
Closing this issue as `flogo ensure` will download updates if needed and `flogo ensure -update` will also update to the latest version (unless there are other constraints in the Gopkg.toml)
