### ISSUE TITLE
flogo install fails

### ISSUE THREAD

**Issue by anshulsharmas** [TIBCOSoftware/flogo-cli#60]
Hi,
I am trying to install activities through cli but getting below errors.
Any suggestions?

`flogo install github.com/TIBCOSoftware/flogo-contrib/activity/log
`
```
skipping insecure protocol: git://github.com/TIBCOSoftware/flogo-contrib
skipping insecure protocol: http://github.com/TIBCOSoftware/flogo-contrib
FATAL: command "fetch" failed: vcs probe failed, tried: https://github.com/TIBCOSoftware/flogo-contrib,ssh://github.com/TIBCOSoftware/flogo-contrib
FATAL: command "vendor" failed: exit status 1
FATAL: command "install" failed: exit status 1
```

**Comment by fcastill** [comment]
It seems like an issue with git. I've faced a similar issue once with go/git when using a VPN, disconnecting from the VPN did the trick.

Also, github servers were having issues earlier today so maybe if you try again now it will work.

**Comment by anshulsharmas** [comment]
I downloaded the flogo-contrib & built the binaries again.
It worked this time. Thanks.
