### ISSUE TITLE
CRASH observed when 2 concurrent clients querying flogo based application

### ISSUE THREAD

**Issue by rameshpolishetti** [TIBCOSoftware/flogo-cli#71]
Flogo application is crashing when 2 concurrent client hitting PUT & GET requests.

Environment: MAC
Attached zip contains necessary files: flowapp-crash-flogo.json & crash.sh
[flowapp-crash.zip](https://github.com/TIBCOSoftware/flogo-cli/files/1420664/flowapp-crash.zip)

**Steps to reproduce the issue**:

**Step-1**:
flogo create -f flowapp-crash-flogo.json flowAppCrash
cd flowAppCrash
flogo build
cd bin
export FLOGO_LOG_LEVEL=ERROR
./flowappcrash

**Step-2**:

Start new terminal & run ./crash.sh
Start 2nd terminal & run ./crash.sh

**You should able see flow app is crashing in 1-2 mins**.

**Comment by mellistibco** [comment]
@rameshpolishetti I've updated the app to use the new flow mappings, etc. I was not able to reproduce the issue you've run into... I've attached an updated app.
[crash_gw_flogo_tgr_1.json.zip](https://github.com/TIBCOSoftware/flogo-cli/files/1548911/crash_gw_flogo_tgr_1.json.zip)

**Comment by rameshpolishetti** [comment]
@mellistibco I have tried with the attached app which uses flow mappings, I don't see CRASH now.
Closing the issue.
